routes/web.php
<?php

use App\Http\Controllers\EmployeeController;
use App\Http\Controllers\PositionController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('dashboard');
});
Route::resource('position',PositionController::class);
Route::resource('employee',EmployeeController::class);

resources/views/dashboard.blade.php
@extends('layout.app')
@section('content')
{{-- <div class="row mb-3">
    <!-- Earnings (Monthly) Card Example -->
    <div class="col-xl-3 col-md-6 mb-4">
      <div class="card h-100">
        <div class="card-body">
          <div class="row align-items-center">
            <div class="col mr-2">
              <div class="text-xs font-weight-bold text-uppercase mb-1">Earnings (Monthly)</div>
              <div class="h5 mb-0 font-weight-bold text-gray-800">$40,000</div>
              <div class="mt-2 mb-0 text-muted text-xs">
                <span class="text-success mr-2"><i class="fa fa-arrow-up"></i> 3.48%</span>
                <span>Since last month</span>
              </div>
            </div>
            <div class="col-auto">
              <i class="fas fa-calendar fa-2x text-primary"></i>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- Earnings (Annual) Card Example -->
    <div class="col-xl-3 col-md-6 mb-4">
      <div class="card h-100">
        <div class="card-body">
          <div class="row no-gutters align-items-center">
            <div class="col mr-2">
              <div class="text-xs font-weight-bold text-uppercase mb-1">Sales</div>
              <div class="h5 mb-0 font-weight-bold text-gray-800">650</div>
              <div class="mt-2 mb-0 text-muted text-xs">
                <span class="text-success mr-2"><i class="fas fa-arrow-up"></i> 12%</span>
                <span>Since last years</span>
              </div>
            </div>
            <div class="col-auto">
              <i class="fas fa-shopping-cart fa-2x text-success"></i>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- New User Card Example -->
    <div class="col-xl-3 col-md-6 mb-4">
      <div class="card h-100">
        <div class="card-body">
          <div class="row no-gutters align-items-center">
            <div class="col mr-2">
              <div class="text-xs font-weight-bold text-uppercase mb-1">New User</div>
              <div class="h5 mb-0 mr-3 font-weight-bold text-gray-800">366</div>
              <div class="mt-2 mb-0 text-muted text-xs">
                <span class="text-success mr-2"><i class="fas fa-arrow-up"></i> 20.4%</span>
                <span>Since last month</span>
              </div>
            </div>
            <div class="col-auto">
              <i class="fas fa-users fa-2x text-info"></i>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- Pending Requests Card Example -->
    <div class="col-xl-3 col-md-6 mb-4">
      <div class="card h-100">
        <div class="card-body">
          <div class="row no-gutters align-items-center">
            <div class="col mr-2">
              <div class="text-xs font-weight-bold text-uppercase mb-1">Pending Requests</div>
              <div class="h5 mb-0 font-weight-bold text-gray-800">18</div>
              <div class="mt-2 mb-0 text-muted text-xs">
                <span class="text-danger mr-2"><i class="fas fa-arrow-down"></i> 1.10%</span>
                <span>Since yesterday</span>
              </div>
            </div>
            <div class="col-auto">
              <i class="fas fa-comments fa-2x text-warning"></i>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- Area Chart -->
    <div class="col-xl-8 col-lg-7">
      <div class="card mb-4">
        <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
          <h6 class="m-0 font-weight-bold text-primary">Monthly Recap Report</h6>
          <div class="dropdown no-arrow">
            <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown"
              aria-haspopup="true" aria-expanded="false">
              <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in"
              aria-labelledby="dropdownMenuLink">
              <div class="dropdown-header">Dropdown Header:</div>
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </div>
        </div>
        <div class="card-body">
          <div class="chart-area">
            <canvas id="myAreaChart"></canvas>
          </div>
        </div>
      </div>
    </div>
    <!-- Pie Chart -->
    <div class="col-xl-4 col-lg-5">
      <div class="card mb-4">
        <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
          <h6 class="m-0 font-weight-bold text-primary">Products Sold</h6>
          <div class="dropdown no-arrow">
            <a class="dropdown-toggle btn btn-primary btn-sm" href="#" role="button" id="dropdownMenuLink"
              data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Month <i class="fas fa-chevron-down"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in"
              aria-labelledby="dropdownMenuLink">
              <div class="dropdown-header">Select Periode</div>
              <a class="dropdown-item" href="#">Today</a>
              <a class="dropdown-item" href="#">Week</a>
              <a class="dropdown-item active" href="#">Month</a>
              <a class="dropdown-item" href="#">This Year</a>
            </div>
          </div>
        </div>
        <div class="card-body">
          <div class="mb-3">
            <div class="small text-gray-500">Oblong T-Shirt
              <div class="small float-right"><b>600 of 800 Items</b></div>
            </div>
            <div class="progress" style="height: 12px;">
              <div class="progress-bar bg-warning" role="progressbar" style="width: 80%" aria-valuenow="80"
                aria-valuemin="0" aria-valuemax="100"></div>
            </div>
          </div>
          <div class="mb-3">
            <div class="small text-gray-500">Gundam 90'Editions
              <div class="small float-right"><b>500 of 800 Items</b></div>
            </div>
            <div class="progress" style="height: 12px;">
              <div class="progress-bar bg-success" role="progressbar" style="width: 70%" aria-valuenow="70"
                aria-valuemin="0" aria-valuemax="100"></div>
            </div>
          </div>
          <div class="mb-3">
            <div class="small text-gray-500">Rounded Hat
              <div class="small float-right"><b>455 of 800 Items</b></div>
            </div>
            <div class="progress" style="height: 12px;">
              <div class="progress-bar bg-danger" role="progressbar" style="width: 55%" aria-valuenow="55"
                aria-valuemin="0" aria-valuemax="100"></div>
            </div>
          </div>
          <div class="mb-3">
            <div class="small text-gray-500">Indomie Goreng
              <div class="small float-right"><b>400 of 800 Items</b></div>
            </div>
            <div class="progress" style="height: 12px;">
              <div class="progress-bar bg-info" role="progressbar" style="width: 50%" aria-valuenow="50"
                aria-valuemin="0" aria-valuemax="100"></div>
            </div>
          </div>
          <div class="mb-3">
            <div class="small text-gray-500">Remote Control Car Racing
              <div class="small float-right"><b>200 of 800 Items</b></div>
            </div>
            <div class="progress" style="height: 12px;">
              <div class="progress-bar bg-success" role="progressbar" style="width: 30%" aria-valuenow="30"
                aria-valuemin="0" aria-valuemax="100"></div>
            </div>
          </div>
        </div>
        <div class="card-footer text-center">
          <a class="m-0 small text-primary card-link" href="#">View More <i
              class="fas fa-chevron-right"></i></a>
        </div>
      </div>
    </div>
    <!-- Invoice Example -->
    <div class="col-xl-8 col-lg-7 mb-4">
      <div class="card">
        <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
          <h6 class="m-0 font-weight-bold text-primary">Invoice</h6>
          <a class="m-0 float-right btn btn-danger btn-sm" href="#">View More <i
              class="fas fa-chevron-right"></i></a>
        </div>
        <div class="table-responsive">
          <table class="table align-items-center table-flush">
            <thead class="thead-light">
              <tr>
                <th>Order ID</th>
                <th>Customer</th>
                <th>Item</th>
                <th>Status</th>
                <th>Action</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td><a href="#">RA0449</a></td>
                <td>Udin Wayang</td>
                <td>Nasi Padang</td>
                <td><span class="badge badge-success">Delivered</span></td>
                <td><a href="#" class="btn btn-sm btn-primary">Detail</a></td>
              </tr>
              <tr>
                <td><a href="#">RA5324</a></td>
                <td>Jaenab Bajigur</td>
                <td>Gundam 90' Edition</td>
                <td><span class="badge badge-warning">Shipping</span></td>
                <td><a href="#" class="btn btn-sm btn-primary">Detail</a></td>
              </tr>
              <tr>
                <td><a href="#">RA8568</a></td>
                <td>Rivat Mahesa</td>
                <td>Oblong T-Shirt</td>
                <td><span class="badge badge-danger">Pending</span></td>
                <td><a href="#" class="btn btn-sm btn-primary">Detail</a></td>
              </tr>
              <tr>
                <td><a href="#">RA1453</a></td>
                <td>Indri Junanda</td>
                <td>Hat Rounded</td>
                <td><span class="badge badge-info">Processing</span></td>
                <td><a href="#" class="btn btn-sm btn-primary">Detail</a></td>
              </tr>
              <tr>
                <td><a href="#">RA1998</a></td>
                <td>Udin Cilok</td>
                <td>Baby Powder</td>
                <td><span class="badge badge-success">Delivered</span></td>
                <td><a href="#" class="btn btn-sm btn-primary">Detail</a></td>
              </tr>
            </tbody>
          </table>
        </div>
        <div class="card-footer"></div>
      </div>
    </div>
    <!-- Message From Customer-->
    <div class="col-xl-4 col-lg-5 ">
      <div class="card">
        <div class="card-header py-4 bg-primary d-flex flex-row align-items-center justify-content-between">
          <h6 class="m-0 font-weight-bold text-light">Message From Customer</h6>
        </div>
        <div>
          <div class="customer-message align-items-center">
            <a class="font-weight-bold" href="#">
              <div class="text-truncate message-title">Hi there! I am wondering if you can help me with a
                problem I've been having.</div>
              <div class="small text-gray-500 message-time font-weight-bold">Udin Cilok · 58m</div>
            </a>
          </div>
          <div class="customer-message align-items-center">
            <a href="#">
              <div class="text-truncate message-title">But I must explain to you how all this mistaken idea
              </div>
              <div class="small text-gray-500 message-time">Nana Haminah · 58m</div>
            </a>
          </div>
          <div class="customer-message align-items-center">
            <a class="font-weight-bold" href="#">
              <div class="text-truncate message-title">Lorem ipsum dolor sit amet, consectetur adipiscing elit
              </div>
              <div class="small text-gray-500 message-time font-weight-bold">Jajang Cincau · 25m</div>
            </a>
          </div>
          <div class="customer-message align-items-center">
            <a class="font-weight-bold" href="#">
              <div class="text-truncate message-title">At vero eos et accusamus et iusto odio dignissimos
                ducimus qui blanditiis
              </div>
              <div class="small text-gray-500 message-time font-weight-bold">Udin Wayang · 54m</div>
            </a>
          </div>
          <div class="card-footer text-center">
            <a class="m-0 small text-primary card-link" href="#">View More <i
                class="fas fa-chevron-right"></i></a>
          </div>
        </div>
      </div>
    </div>
</div> --}}
  <!--Row-->
@endsection

resources/views/employee.blade.php
@extends('layout.app')

@section('css')
    <link href="{{ asset('vendor/datatables/dataTables.bootstrap4.min.css') }}" rel="stylesheet">
@endsection
@section('breadcrumb')
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Jabatan</h1>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{ url('/') }}">Dashboard</a></li>
            <li class="breadcrumb-item active" aria-current="page">Jabatan</li>
        </ol>
    </div>
@endsection
@section('content')
    <div class="card sm mb-4">
        <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
            <h6 class="m-0 font-weight-bold text-primary"></h6>
        </div>
        <div class="card-body">
            <div class="table-responsive p-3">
                <a href="{{ route('employee.create') }}" class="btn btn-primary mb-3">Tambah Data +</a>
                <table class="table align-items-center table-flush" id="dataTable">
                    <thead class="thead-light">
                        <tr>
                            <th>No.</th>
                            <th>NIP</th>
                            <th>Nama</th>
                            <th>Tahun Lahir</th>
                            <th>Alamat</th>
                            <th>No Telp</th>
                            <th>Agama</th>
                            <th>Status</th>
                            <th class="text-center">Aksi</th>
                        </tr>
                    </thead>
                </table>
            </div>
        </div>
    </div>
@endsection

@push('js')
    <script src="{{ asset('vendor/datatables/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('vendor/datatables/dataTables.bootstrap4.min.js') }}"></script>
    <script>
        $(document).ready(function() {
            $('#dataTable').DataTable({
                processing: true,
                serverSide: true,
                ajax: "{{ route('employee.index') }}",
                columns: [{
                        data: 'DT_RowIndex',
                        orderable: false,
                        searchable: false,
                        className: "text-center"
                    },
                    {
                        data: 'nip'
                    },
                    {
                        data: 'nama'
                    },
                    {
                        data: 'tahun_lahir'
                    },
                    {
                        data: 'alamat'
                    },
                    {
                        data: 'nomor_telepon'
                    },
                    {
                        data: 'agama'
                    },
                    {
                        data: 'status',
                        render: function(data, type, row) {
                            return data == '1' ?
                                '<div class="bg-success rounded text-center text-white"> Aktif </div>' :
                                '<div class="bg-danger rounded text-center text-white"> Tidak Aktif </div>';
                        }
                    },
                    {
                        data: null,
                        render: function(data, type, row) {
                            var editUrl = "{{ route('employee.edit', ':id') }}";
                            editUrl = editUrl.replace(':id', row.id);
                            return '<a href="' + editUrl +
                                '" class="bg-primary rounded px-2 text-white d-flex m-1"> Edit <i class="pl-2 fs-5 bi bi-pencil-square"></i></a>';
                        }
                    }

                ]
            });
        });
    </script>
@endpush

resources/views/employeeCreate.blade.php
@extends('layout.app')

@section('css')
    <link href="{{ asset('vendor/datatables/dataTables.bootstrap4.min.css') }}" rel="stylesheet">
@endsection

@section('breadcrumb')
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Tambah Jabatan</h1>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{ url('/') }}">Dashboard</a></li>
            <li class="breadcrumb-item active" aria-current="page">Jabatan</li>
        </ol>
    </div>
@endsection

@section('content')
    <div class="card p-5">
        <form action="{{ route('employee.store') }}" method="POST" enctype="multipart/form-data">
            @csrf
            <div class="mb-3">
                <label for="nama" class="form-label">Nama</label>
                <input type="text" class="form-control" id="nama" name="nama" value="{{ old('nama') }}">
            </div>
            <div class="mb-3">
                <label for="nip" class="form-label">NIP</label>
                <input type="text" class="form-control" id="nip" name="nip" value="{{ old('nip') }}">
            </div>
            <div class="mb-3">
                @php
                    $data = \App\Models\Position::all();
                @endphp
                <label for="position_id" class="form-group">Position</label>
                <select class="form-control" id="position_id" name="position_id">
                    <option selected disabled>Pilih Posisi</option>
                    @foreach ($data as $item)
                        <option value="{{ $item->id }}" >{{ $item->name }}</option>
                    @endforeach
                </select>
            </div>
            <div class="mb-3">
                <label for="tahun_lahir" class="form-group">Tahun Lahir</label>
                <select class="form-control" id="tahun_lahir" name="tahun_lahir">
                    <option selected disabled>Pilih Tahun</option>
                    @for ($tahun = 1990; $tahun <= date('Y'); $tahun++)
                        <option value="{{ $tahun }}" {{ old('tahun_lahir') == $tahun ? 'selected' : '' }}>
                            {{ $tahun }}</option>
                    @endfor
                </select>
            </div>
            <div class="mb-3">
                <label for="alamat" class="form-label">Alamat</label>
                <textarea class="form-control" id="alamat" name="alamat" rows="3">{{ old('alamat') }}</textarea>
            </div>
            <div class="mb-3">
                <label for="nomor_telepon" class="form-label">Nomor Telepon</label>
                <input type="text" class="form-control" id="nomor_telepon" name="nomor_telepon"
                    value="{{ old('nomor_telepon') }}">
            </div>
            <div class="mb-3">
                <label for="agama" class="form-label">Agama</label>
                <div class="form-check">
                    <input class="form-check-input" type="radio" name="agama" id="islam" value="Islam"
                        {{ old('agama') == 'Islam' ? 'checked' : '' }}>
                    <label class="form-check-label" for="islam">Islam</label>
                </div>
                <div class="form-check">
                    <input class="form-check-input" type="radio" name="agama" id="Kristen" value="Kristen"
                        {{ old('agama') == 'Kristen' ? 'checked' : '' }}>
                    <label class="form-check-label" for="Kristen">Kristen</label>
                </div>
                <div class="form-check">
                    <input class="form-check-input" type="radio" name="agama" id="Buddha" value="Buddha"
                        {{ old('agama') == 'Buddha' ? 'checked' : '' }}>
                    <label class="form-check-label" for="Buddha">Buddha</label>
                </div>
                <div class="form-check">
                    <input class="form-check-input" type="radio" name="agama" id="Hindu" value="Hindu"
                        {{ old('agama') == 'Hindu' ? 'checked' : '' }}>
                    <label class="form-check-label" for="Hindu">Hindu</label>
                </div>
                <div class="form-check">
                    <input class="form-check-input" type="radio" name="agama" id="Konghucu" value="Konghucu"
                        {{ old('agama') == 'Konghucu' ? 'checked' : '' }}>
                    <label class="form-check-label" for="Konghucu">Konghucu</label>
                </div>
                <!-- Tambahkan pilihan agama lainnya sesuai kebutuhan -->
            </div>
            <div class="mb-3">
                <label for="status" class="form-group">Status</label>
                <select class="form-control" id="status" name="status">
                    <option value="1" {{ old('status') == '1' ? 'selected' : '' }}>Aktif</option>
                    <option value="0" {{ old('status') == '0' ? 'selected' : '' }}>Tidak Aktif</option>
                </select>
            </div>
            <div class="mb-3">
                <label for="foto_ktp" class="form-label">Foto KTP</label>
                <input class="form-control" type="file" id="foto_ktp" name="foto_ktp"
                    value="{{ old('foto_ktp') }}" placeholder="Masukkan Foto">
            </div>
            <button type="submit" class="btn btn-primary">Simpan</button>
        </form>
    </div>
@endsection

resources/views/employeeEdit.blade.php
@extends('layout.app')

@section('css')
    <link href="{{ asset('vendor/datatables/dataTables.bootstrap4.min.css') }}" rel="stylesheet">
@endsection
@section('breadcrumb')
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Edit Jabatan </h1>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{ url('/') }}">Dashboard</a></li>
            <li class="breadcrumb-item active" aria-current="page">Jabatan</li>
        </ol>
    </div>
@endsection
@section('content')
    <div class="card p-5">
        <form action="{{ route('employee.update', $employee->id) }}" method="POST" enctype="multipart/form-data">
            @csrf
            @method('PUT')
            <div class="mb-3">
                <label for="nama" class="form-label">Nama</label>
                <input type="text" class="form-control" id="nama" name="nama" value="{{ $employee->nama }}">
            </div>
            <div class="mb-3">
                <label for="nip" class="form-label">NIP</label>
                <input type="text" class="form-control" id="nip" name="nip" value="{{ $employee->nip }}">
            </div>
            <div class="mb-3">
                @php
                    $data = \App\Models\Position::all();
                @endphp
                <label for="position_id" class="form-group">Position</label>
                <select class="form-control" id="position_id" name="position_id">
                    <option selected disabled>Pilih Posisi</option>
                    @foreach ($data as $item)
                        <option value="{{ $item->id }}" {{ $employee->position_id == $item->id ? 'selected' : '' }}>
                            {{ $item->name }}</option>
                    @endforeach
                </select>
            </div>
            <div class="mb-3">
                <label for="tahun_lahir" class="form-group">Tahun Lahir</label>
                <select class="form-control" id="tahun_lahir" name="tahun_lahir">
                    <option selected disabled>Pilih Tahun</option>
                    @for ($tahun = 1990; $tahun <= date('Y'); $tahun++)
                        <option value="{{ $tahun }}" {{ $employee->tahun_lahir == $tahun ? 'selected' : '' }}>
                            {{ $tahun }}</option>
                    @endfor
                </select>
            </div>
            <div class="mb-3">
                <label for="alamat" class="form-label">Alamat</label>
                <textarea class="form-control" id="alamat" name="alamat" rows="3">{{ $employee->alamat }}</textarea>
            </div>
            <div class="mb-3">
                <label for="nomor_telepon" class="form-label">Nomor Telepon</label>
                <input type="text" class="form-control" id="nomor_telepon" name="nomor_telepon"
                    value="{{ $employee->nomor_telepon }}">
            </div>
            <div class="mb-3">
                <label for="agama" class="form-label">Agama</label>
                <div class="form-check">
                    <input class="form-check-input" type="radio" name="agama" id="islam" value="Islam"
                        {{ $employee->agama == 'Islam' ? 'checked' : '' }}>
                    <label class="form-check-label" for="islam">Islam</label>
                </div>
                <div class="form-check">
                    <input class="form-check-input" type="radio" name="agama" id="kristen" value="Kristen"
                        {{ $employee->agama == 'Kristen' ? 'checked' : '' }}>
                    <label class="form-check-label" for="kristen">Kristen</label>
                </div>
                <div class="form-check">
                    <input class="form-check-input" type="radio" name="agama" id="Katolik" value="Katolik"
                        {{ $employee->agama == 'Katolik' ? 'checked' : '' }}>
                    <label class="form-check-label" for="Katolik">Katolik</label>
                </div>
                <div class="form-check">
                    <input class="form-check-input" type="radio" name="agama" id="hindu" value="Hindu"
                        {{ $employee->agama == 'Hindu' ? 'checked' : '' }}>
                    <label class="form-check-label" for="hindu">Hindu</label>
                </div>
                <div class="form-check">
                    <input class="form-check-input" type="radio" name="agama" id="Buddha" value="Buddha"
                        {{ $employee->agama == 'Buddha' ? 'checked' : '' }}>
                    <label class="form-check-label" for="Buddha">Buddha</label>
                </div>
            </div>
            <div class="mb-3">
                <label for="status" class="form-group">Status</label>
                <select class="form-control" id="status" name="status">
                    <option value="1" {{ $employee->status ? 'selected' : '' }}>Aktif</option>
                    <option value="0" {{ !$employee->status ? 'selected' : '' }}>Tidak Aktif</option>
                </select>

            </div>
            <div class="mb-3">
                <label for="foto_ktp" class="form-label">Foto KTP</label>
                <input class="form-control" type="file" id="foto_ktp" name="foto_ktp"
                    value="{{ $employee->foto_ktp }}" placeholder="Masukkan Foto">{{ $employee->foto_ktp }}</input>
            </div>

            <div class="d-flex justify-content-end pe-0 me-0 text-center">
                <a class="btn btn-danger btn-sm w-auto px-3 me-2 mx-1 d-flex align-items-center" data-bs-toggle="modal"
                    href="#exampleModal" role="button">Hapus</a>
                <a href="{{ route('employee.index') }}" class="btn btn-secondary mx-1">Kembali</a>
                <button type="submit" class="btn btn-primary mx-1">Simpan Perubahan</button>
            </div>


        </form>


        <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel"
            aria-hidden="true">
            <div class="modal-dialog ">
                <div class="modal-content">
                    <div class="modal-header tw-justify-between">
                        <h5 class="modal-title" id="exampleModalLabel">Hapus data</h5>
                        <button type="button" class="btn-close btn-sm tw-text-black" data-bs-dismiss="modal"
                            aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        Apakah anda yakin ingin menghapus data ?
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary btn-sm tw-bg-[#6c757d]"
                            data-bs-dismiss="modal">Close</button>
                        <form action="{{ route('employee.destroy', $employee->id) }}" method="POST">
                            @csrf
                            @method('DELETE')
                            <button type="submit" class="btn btn-danger btn-sm tw-bg-[#dc3545]">Hapus</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/position.blade.php
@extends('layout.app')

@section('css')
  <link href="{{ asset('vendor/datatables/dataTables.bootstrap4.min.css') }}" rel="stylesheet">
@endsection
@section('breadcrumb')
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Jabatan</h1>
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{ url('/') }}">Dashboard</a></li>
        <li class="breadcrumb-item active" aria-current="page">Jabatan</li>
    </ol>
</div>
@endsection
@section('content')
<div class="card sm mb-4">
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
        <h6 class="m-0 font-weight-bold text-primary"></h6>
    </div>
    <div class="card-body">
        <div class="table-responsive p-3">
            <table class="table align-items-center table-flush" id="dataTable">
              <thead class="thead-light">
                <tr>
                  <th>No.</th>
                  <th>Name</th>
                </tr>
              </thead>
            </table>
          </div>
    </div>
</div>
@endsection

@push('js')
<script src="{{ asset('vendor/datatables/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('vendor/datatables/dataTables.bootstrap4.min.js') }}"></script>
<script>
    $('#dataTable').DataTable({
        processing: true,
        serverSide: true,
        ajax: "{{ route('position.index') }}",
        columns: [
            { data: 'DT_RowIndex', orderable: false, searchable: false, className: "text-center"},
            { data: 'name' }
        ]
    })
</script>
@endpush